import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title :{
    default:"Experimental-form",
    template :"%s | Expermental-form ",
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Navbar/>
        </header>
        {children}
        <footer style={{
          textAlign:"center",
          padding:"1rem"
        }}>
          <h3>All CopyRight reserved &copy; by {'Saransh Regmi'}</h3>
        </footer>
        </body>
    </html>
  )
}
